"""Bounded connector tool catalog partition."""

from .tool_def_model import ConnectorToolDef

TOOL_DEFS: tuple[ConnectorToolDef, ...] = (
    ConnectorToolDef(
        "browser",
        "browser_read_url",
        "Read public URL",
        "read",
        "Fetch readable text from a public URL.",
    ),
    ConnectorToolDef(
        "browser",
        "browser_open_url",
        "Open URL",
        "read",
        "Open a URL in the Playwright browser.",
    ),
    ConnectorToolDef(
        "browser",
        "browser_snapshot",
        "Snapshot page",
        "read",
        "Read page text and visible controls.",
    ),
    ConnectorToolDef(
        "browser",
        "browser_get_text",
        "Read page text",
        "read",
        "Read visible text from the current browser page.",
    ),
    ConnectorToolDef(
        "browser",
        "browser_click",
        "Click page",
        "write",
        "Click a visible browser element.",
    ),
    ConnectorToolDef(
        "browser",
        "browser_type",
        "Fill field",
        "write",
        "Type into or fill a browser field.",
    ),
    ConnectorToolDef(
        "browser",
        "browser_select",
        "Select option",
        "write",
        "Select a dropdown option.",
    ),
    ConnectorToolDef(
        "browser",
        "browser_upload_file",
        "Upload file",
        "write",
        "Upload a local file through a file input.",
    ),
    ConnectorToolDef(
        "browser", "browser_wait", "Wait", "read", "Wait for time or an element."
    ),
    ConnectorToolDef(
        "browser",
        "browser_screenshot",
        "Screenshot",
        "read",
        "Capture a browser screenshot.",
    ),
    ConnectorToolDef(
        "browser",
        "browser_close",
        "Close browser",
        "write",
        "Close the browser session.",
    ),
    ConnectorToolDef(
        "github",
        "github_search",
        "Search GitHub",
        "read",
        "Search issues, pull requests, or repositories.",
    ),
    ConnectorToolDef(
        "github",
        "github_get_issue",
        "Read issue",
        "read",
        "Read a GitHub issue or pull request.",
    ),
    ConnectorToolDef(
        "github",
        "github_create_issue",
        "Create issue",
        "write",
        "Create a GitHub issue.",
    ),
    ConnectorToolDef(
        "github",
        "github_reply",
        "Reply on issue/PR",
        "write",
        "Comment on an issue or pull request.",
    ),
    ConnectorToolDef(
        "github",
        "github_review",
        "Review a PR",
        "write",
        "Submit a pull-request review (approve / request changes / comment).",
    ),
    ConnectorToolDef(
        "github",
        "github_list_commits",
        "List commits",
        "read",
        "List a repository's recent commits (for activity summaries).",
    ),
    ConnectorToolDef(
        "github",
        "github_clone",
        "Clone a repo",
        "read",
        "Clone a repository into a session folder to explore the code.",
    ),
    ConnectorToolDef(
        "github",
        "github_pull",
        "Update a clone",
        "read",
        "Fast-forward an existing clone to the latest commits.",
    ),
    ConnectorToolDef(
        "email",
        "email_list_folders",
        "List folders",
        "read",
        "List mailbox folders and message counts.",
    ),
    ConnectorToolDef(
        "email",
        "email_search",
        "Search mail",
        "read",
        "Search the mailbox; returns envelopes, never marks messages read.",
    ),
    ConnectorToolDef(
        "email",
        "email_read",
        "Read message",
        "read",
        "Read one email's headers, body, and attachment list.",
    ),
    ConnectorToolDef(
        "email",
        "email_download_attachment",
        "Save attachment",
        "write",
        "Save one attachment into the session folder (requires approval).",
    ),
    ConnectorToolDef(
        "email",
        "email_send",
        "Send email",
        "write",
        "Send or reply to an email via SMTP (requires approval).",
        target_arg="to",
    ),
    ConnectorToolDef(
        "gmail",
        "gmail_search_messages",
        "Search Gmail",
        "read",
        "Search Gmail messages.",
    ),
    ConnectorToolDef(
        "gmail", "gmail_get_message", "Read message", "read", "Read a Gmail message."
    ),
    ConnectorToolDef(
        "gmail",
        "gmail_send_email",
        "Send email",
        "write",
        "Send an email through Gmail.",
        target_arg="to",
    ),
    ConnectorToolDef(
        "google_calendar",
        "gcal_list_events",
        "List events",
        "read",
        "List Google Calendar events.",
    ),
    ConnectorToolDef(
        "google_calendar",
        "gcal_free_busy",
        "Check availability",
        "read",
        "Look up busy intervals across calendars.",
    ),
    ConnectorToolDef(
        "google_calendar",
        "gcal_create_event",
        "Create event",
        "write",
        "Create a Google Calendar event.",
    ),
    ConnectorToolDef(
        "google_calendar",
        "gcal_update_event",
        "Update event",
        "write",
        "Change fields of an existing event.",
    ),
    ConnectorToolDef(
        "google_calendar",
        "gcal_delete_event",
        "Delete event",
        "write",
        "Delete a calendar event.",
    ),
    ConnectorToolDef(
        "outlook",
        "outlook_search_messages",
        "Search Outlook",
        "read",
        "Search Outlook messages.",
    ),
    ConnectorToolDef(
        "outlook",
        "outlook_send_mail",
        "Send mail",
        "write",
        "Send mail through Outlook.",
        target_arg="to",
    ),
    ConnectorToolDef(
        "outlook",
        "outlook_list_events",
        "List events",
        "read",
        "List upcoming Outlook calendar events.",
    ),
    ConnectorToolDef(
        "outlook",
        "outlook_create_event",
        "Create event",
        "write",
        "Create an Outlook calendar event.",
    ),
    ConnectorToolDef(
        "outlook",
        "outlook_update_event",
        "Update event",
        "write",
        "Change fields of an existing event.",
    ),
    ConnectorToolDef(
        "outlook",
        "outlook_delete_event",
        "Delete event",
        "write",
        "Delete a calendar event.",
    ),
    ConnectorToolDef(
        "outlook",
        "outlook_respond_event",
        "Respond to invite",
        "write",
        "Accept, decline, or tentatively accept a meeting invite.",
    ),
    ConnectorToolDef(
        "jira", "jira_search_issues", "Search issues", "read", "Search Jira issues."
    ),
    ConnectorToolDef(
        "jira", "jira_get_issue", "Read issue", "read", "Read a Jira issue."
    ),
    ConnectorToolDef(
        "jira", "jira_create_issue", "Create issue", "write", "Create a Jira issue."
    ),
    # -- jira via the Atlassian hosted MCP server (one-click path) ---------------
    # PINNED allowlist (UX-DECISIONS §42): tool names are `mcp__<connector>__<vendor
    # tool>` exactly as mcp/tools.py builds them; anything the vendor ships that is
    # not listed here never reaches a session. Which set is live (these vs the
    # jira_* REST tools above) follows the profile's mode — see tool_dicts.
    ConnectorToolDef(
        "jira",
        "mcp__jira__getVisibleJiraProjects",
        "List projects",
        "read",
        "List Jira projects you can access.",
    ),
    ConnectorToolDef(
        "jira",
        "mcp__jira__searchJiraIssuesUsingJql",
        "Search issues",
        "read",
        "Search Jira issues using JQL.",
    ),
    ConnectorToolDef(
        "jira",
        "mcp__jira__getJiraIssue",
        "Read issue",
        "read",
        "Read a Jira issue.",
    ),
    ConnectorToolDef(
        "jira",
        "mcp__jira__getTransitionsForJiraIssue",
        "List transitions",
        "read",
        "List available workflow transitions for an issue.",
    ),
    ConnectorToolDef(
        "jira",
        "mcp__jira__createJiraIssue",
        "Create issue",
        "write",
        "Create a Jira issue.",
    ),
    ConnectorToolDef(
        "jira",
        "mcp__jira__editJiraIssue",
        "Update issue",
        "write",
        "Update fields on an existing issue.",
    ),
    ConnectorToolDef(
        "jira",
        "mcp__jira__addCommentToJiraIssue",
        "Comment",
        "write",
        "Add a comment to an issue.",
    ),
    ConnectorToolDef(
        "jira",
        "mcp__jira__transitionJiraIssue",
        "Transition issue",
        "write",
        "Move an issue through its workflow.",
    ),
    # -- monday.com (MCP-backed only; pinned subset of their 60+ tool catalog) ----
    ConnectorToolDef(
        "monday",
        "mcp__monday__get_user_context",
        "Who am I",
        "read",
        "Read the signed-in user, account, and their boards.",
    ),
    ConnectorToolDef(
        "monday",
        "mcp__monday__search",
        "Search",
        "read",
        "Search boards, docs, forms, and folders.",
    ),
    ConnectorToolDef(
        "monday",
        "mcp__monday__get_board_info",
        "Read board",
        "read",
        "Read a board's columns, groups, views, and owners.",
    ),
    ConnectorToolDef(
        "monday",
        "mcp__monday__get_board_items_page",
        "List items",
        "read",
        "Page through the items on a board.",
    ),
    ConnectorToolDef(
        "monday",
        "mcp__monday__board_insights",
        "Board insights",
        "read",
        "Aggregate, filter, and group board data.",
    ),
    ConnectorToolDef(
        "monday",
        "mcp__monday__get_updates",
        "Read updates",
        "read",
        "Read updates (comments) from an item or board.",
    ),
    ConnectorToolDef(
        "monday",
        "mcp__monday__create_item",
        "Create item",
        "write",
        "Create an item on a board.",
    ),
    ConnectorToolDef(
        "monday",
        "mcp__monday__change_item_column_values",
        "Update item",
        "write",
        "Change column values on an item.",
    ),
    ConnectorToolDef(
        "monday",
        "mcp__monday__create_update",
        "Post update",
        "write",
        "Post a comment or reply on an item.",
    ),
    # -- asana via their hosted V2 MCP server (one-click path; the asana_* REST
    # tools below stay the manual-token set — profile mode picks, as with jira) ---
    ConnectorToolDef(
        "asana",
        "mcp__asana__get_me",
        "Who am I",
        "read",
        "Read the signed-in Asana user.",
    ),
    ConnectorToolDef(
        "asana",
        "mcp__asana__search_tasks",
        "Search tasks",
        "read",
        "Search tasks across the workspace.",
    ),
    ConnectorToolDef(
        "asana",
        "mcp__asana__get_task",
        "Read task",
        "read",
        "Read a task with its fields and comments.",
    ),
    ConnectorToolDef(
        "asana",
        "mcp__asana__get_my_tasks",
        "My tasks",
        "read",
        "List the signed-in user's tasks.",
    ),
    ConnectorToolDef(
        "asana",
        "mcp__asana__get_project",
        "Read project",
        "read",
        "Read a project's details.",
    ),
    ConnectorToolDef(
        "asana",
        "mcp__asana__get_status_overview",
        "Status overview",
        "read",
        "Read status updates for projects and portfolios.",
    ),
    ConnectorToolDef(
        "asana",
        "mcp__asana__create_tasks",
        "Create tasks",
        "write",
        "Create one or more tasks.",
    ),
    ConnectorToolDef(
        "asana",
        "mcp__asana__update_tasks",
        "Update tasks",
        "write",
        "Update fields on existing tasks.",
    ),
    ConnectorToolDef(
        "asana",
        "mcp__asana__add_comment",
        "Comment",
        "write",
        "Add a comment to a task.",
    ),
)
