"""Bounded connector tool catalog partition."""

from .tool_def_model import ConnectorToolDef

TOOL_DEFS: tuple[ConnectorToolDef, ...] = (
    ConnectorToolDef(
        "confluence",
        "confluence_search",
        "Search pages",
        "read",
        "Search Confluence pages.",
    ),
    ConnectorToolDef(
        "confluence",
        "confluence_get_page",
        "Read page",
        "read",
        "Read a Confluence page.",
    ),
    ConnectorToolDef(
        "confluence",
        "confluence_create_page",
        "Create page",
        "write",
        "Create a Confluence page.",
    ),
    ConnectorToolDef(
        "zendesk", "zendesk_search", "Search Zendesk", "read", "Search Zendesk."
    ),
    ConnectorToolDef(
        "zendesk", "zendesk_get_ticket", "Read ticket", "read", "Read a Zendesk ticket."
    ),
    ConnectorToolDef(
        "zendesk",
        "zendesk_create_ticket",
        "Create ticket",
        "write",
        "Create a Zendesk ticket.",
    ),
    ConnectorToolDef(
        "linear",
        "linear_search_issues",
        "Search issues",
        "read",
        "Search Linear issues.",
    ),
    ConnectorToolDef(
        "linear", "linear_get_issue", "Read issue", "read", "Read a Linear issue."
    ),
    ConnectorToolDef(
        "linear", "linear_list_teams", "List teams", "read", "List Linear teams."
    ),
    ConnectorToolDef(
        "linear",
        "linear_create_issue",
        "Create issue",
        "write",
        "Create a Linear issue.",
    ),
    ConnectorToolDef(
        "gitlab",
        "gitlab_search",
        "Search GitLab",
        "read",
        "Search projects, issues, or merge requests.",
    ),
    ConnectorToolDef(
        "gitlab", "gitlab_get_issue", "Read issue", "read", "Read a GitLab issue."
    ),
    ConnectorToolDef(
        "gitlab",
        "gitlab_get_merge_request",
        "Read merge request",
        "read",
        "Read a GitLab merge request.",
    ),
    ConnectorToolDef(
        "gitlab",
        "gitlab_create_issue",
        "Create issue",
        "write",
        "Create a GitLab issue.",
    ),
    ConnectorToolDef(
        "discord",
        "discord_list_channels",
        "List channels",
        "read",
        "List channels in a Discord server.",
    ),
    ConnectorToolDef(
        "discord",
        "discord_read_messages",
        "Read messages",
        "read",
        "Read recent Discord channel messages.",
    ),
    ConnectorToolDef(
        "discord",
        "discord_send_message",
        "Send message",
        "write",
        "Send a Discord channel message.",
        target_arg="channel_id",
    ),
    ConnectorToolDef(
        "stripe",
        "stripe_search_customers",
        "Search customers",
        "read",
        "Search Stripe customers.",
    ),
    ConnectorToolDef(
        "stripe",
        "stripe_list_charges",
        "List charges",
        "read",
        "List Stripe charges.",
    ),
    ConnectorToolDef(
        "stripe",
        "stripe_list_invoices",
        "List invoices",
        "read",
        "List Stripe invoices.",
    ),
    ConnectorToolDef(
        "asana",
        "asana_list_workspaces",
        "List workspaces",
        "read",
        "List Asana workspaces.",
    ),
    ConnectorToolDef(
        "asana", "asana_search_tasks", "Search tasks", "read", "Search Asana tasks."
    ),
    ConnectorToolDef(
        "asana", "asana_get_task", "Read task", "read", "Read an Asana task."
    ),
    ConnectorToolDef(
        "asana", "asana_create_task", "Create task", "write", "Create an Asana task."
    ),
    ConnectorToolDef(
        "hubspot",
        "hubspot_search",
        "Search CRM",
        "read",
        "Search HubSpot contacts, companies, deals, or tickets.",
    ),
    ConnectorToolDef(
        "hubspot",
        "hubspot_get_object",
        "Read record",
        "read",
        "Read a HubSpot CRM record.",
    ),
    ConnectorToolDef(
        "hubspot",
        "hubspot_create_contact",
        "Create contact",
        "write",
        "Create a HubSpot contact.",
    ),
    ConnectorToolDef(
        "hubspot",
        "hubspot_update_object",
        "Update record",
        "write",
        "Update properties on a CRM record (no deletes).",
    ),
    ConnectorToolDef(
        "hubspot",
        "hubspot_log_note",
        "Log note",
        "write",
        "Log a note on a record's timeline.",
    ),
    ConnectorToolDef(
        "hubspot",
        "hubspot_create_task",
        "Create task",
        "write",
        "Create a HubSpot task.",
    ),
    ConnectorToolDef(
        "dropbox", "dropbox_search", "Search files", "read", "Search Dropbox files."
    ),
    ConnectorToolDef(
        "dropbox",
        "dropbox_list_folder",
        "List folder",
        "read",
        "List a Dropbox folder.",
    ),
    ConnectorToolDef(
        "dropbox",
        "dropbox_read_file",
        "Read file",
        "read",
        "Read a text file from Dropbox.",
    ),
    ConnectorToolDef("box", "box_search", "Search files", "read", "Search Box files."),
    ConnectorToolDef(
        "box", "box_list_folder", "List folder", "read", "List a Box folder."
    ),
    ConnectorToolDef(
        "box", "box_read_file", "Read file", "read", "Read a text file from Box."
    ),
    ConnectorToolDef(
        "quickbooks",
        "quickbooks_query",
        "Query records",
        "read",
        "Run a QuickBooks Online query.",
    ),
    ConnectorToolDef(
        "quickbooks",
        "quickbooks_list_customers",
        "List customers",
        "read",
        "List QuickBooks customers.",
    ),
    ConnectorToolDef(
        "quickbooks",
        "quickbooks_list_invoices",
        "List invoices",
        "read",
        "List recent QuickBooks invoices.",
    ),
    ConnectorToolDef(
        "quickbooks",
        "quickbooks_get_report",
        "Run report",
        "read",
        "Run a QuickBooks financial report.",
    ),
    ConnectorToolDef(
        "whatsapp",
        "whatsapp_send_message",
        "Send message",
        "write",
        "Send a WhatsApp text message.",
        target_arg="to",
    ),
    ConnectorToolDef(
        "whatsapp",
        "whatsapp_send_template",
        "Send template",
        "write",
        "Send an approved WhatsApp template message.",
        target_arg="to",
    ),
    ConnectorToolDef(
        "notion",
        "notion_search",
        "Search",
        "read",
        "Search Notion pages and databases.",
    ),
    ConnectorToolDef(
        "notion",
        "notion_read_page",
        "Read page",
        "read",
        "Read a page's properties and content.",
    ),
    ConnectorToolDef(
        "notion",
        "notion_query_database",
        "Query database",
        "read",
        "Query a Notion database.",
    ),
    ConnectorToolDef(
        "notion",
        "notion_create_page",
        "Create page",
        "write",
        "Create a page under a parent page.",
    ),
    ConnectorToolDef(
        "attio",
        "attio_list_objects",
        "List objects",
        "read",
        "List Attio object types.",
    ),
    ConnectorToolDef(
        "attio",
        "attio_query_records",
        "Query records",
        "read",
        "List/filter records of an object.",
    ),
    ConnectorToolDef(
        "attio",
        "attio_get_record",
        "Read record",
        "read",
        "Read one record by id.",
    ),
    ConnectorToolDef(
        "attio",
        "attio_create_note",
        "Log note",
        "write",
        "Log a note on a record.",
    ),
    ConnectorToolDef(
        "posthog",
        "posthog_query",
        "Run query",
        "read",
        "Run a HogQL analytics query.",
    ),
    ConnectorToolDef(
        "posthog",
        "posthog_list_insights",
        "List insights",
        "read",
        "List saved PostHog insights.",
    ),
    ConnectorToolDef(
        "mixpanel",
        "mixpanel_segmentation",
        "Event counts",
        "read",
        "Mixpanel event counts over a date range.",
    ),
    ConnectorToolDef(
        "mixpanel",
        "mixpanel_top_events",
        "Top events",
        "read",
        "Today's top Mixpanel events.",
    ),
    ConnectorToolDef(
        "amplitude",
        "amplitude_active_users",
        "Active users",
        "read",
        "Amplitude daily active/new users.",
    ),
    ConnectorToolDef(
        "amplitude",
        "amplitude_event_totals",
        "Event totals",
        "read",
        "Daily totals for one Amplitude event.",
    ),
    ConnectorToolDef(
        "apollo",
        "apollo_enrich_person",
        "Enrich person",
        "read",
        "Enrich a person by email or name.",
    ),
    ConnectorToolDef(
        "apollo",
        "apollo_enrich_company",
        "Enrich company",
        "read",
        "Enrich a company by domain.",
    ),
    ConnectorToolDef(
        "apollo",
        "apollo_search_people",
        "Search people",
        "read",
        "Keyword-search Apollo's B2B database.",
    ),
    ConnectorToolDef(
        "hunter",
        "hunter_domain_search",
        "Domain search",
        "read",
        "Find published emails for a domain.",
    ),
    ConnectorToolDef(
        "hunter",
        "hunter_find_email",
        "Find email",
        "read",
        "Find a person's likely email address.",
    ),
    ConnectorToolDef(
        "hunter",
        "hunter_verify_email",
        "Verify email",
        "read",
        "Check whether an email is deliverable.",
    ),
    ConnectorToolDef(
        "clickup",
        "clickup_list_teams",
        "List workspaces",
        "read",
        "List ClickUp workspaces.",
    ),
    ConnectorToolDef(
        "clickup",
        "clickup_list_spaces",
        "List spaces",
        "read",
        "List spaces in a workspace.",
    ),
    ConnectorToolDef(
        "clickup",
        "clickup_list_lists",
        "List lists",
        "read",
        "List task lists in a space.",
    ),
    ConnectorToolDef(
        "clickup",
        "clickup_list_tasks",
        "List tasks",
        "read",
        "List tasks in a list.",
    ),
    ConnectorToolDef(
        "clickup",
        "clickup_get_task",
        "Read task",
        "read",
        "Read one task with subtasks.",
    ),
    ConnectorToolDef(
        "clickup",
        "clickup_create_task",
        "Create task",
        "write",
        "Create a task in a list.",
        target_arg="list_id",
    ),
    ConnectorToolDef(
        "clickup",
        "clickup_update_task",
        "Update task",
        "write",
        "Update a task's name, description, or status.",
        target_arg="task_id",
    ),
    ConnectorToolDef(
        "clickup",
        "clickup_add_comment",
        "Comment",
        "write",
        "Comment on a task.",
        target_arg="task_id",
    ),
    ConnectorToolDef(
        "close",
        "close_search_leads",
        "Search leads",
        "read",
        "Search leads with Close's query syntax.",
    ),
    ConnectorToolDef(
        "close",
        "close_get_lead",
        "Read lead",
        "read",
        "Read one lead with contacts and opportunities.",
    ),
    ConnectorToolDef(
        "close",
        "close_list_opportunities",
        "List opportunities",
        "read",
        "List opportunities, optionally per lead.",
    ),
)
