"""Bounded connector tool catalog partition."""

from .tool_def_model import ConnectorToolDef

TOOL_DEFS: tuple[ConnectorToolDef, ...] = (
    ConnectorToolDef(
        "close",
        "close_create_lead",
        "Create lead",
        "write",
        "Create a lead, optionally with a contact.",
    ),
    ConnectorToolDef(
        "close",
        "close_update_opportunity",
        "Update opportunity",
        "write",
        "Update an opportunity's status or note.",
        target_arg="opportunity_id",
    ),
    ConnectorToolDef(
        "close",
        "close_log_note",
        "Log note",
        "write",
        "Log a note on a lead's timeline.",
        target_arg="lead_id",
    ),
    ConnectorToolDef(
        "figma",
        "figma_get_file",
        "Read file",
        "read",
        "Read a file's pages and frames.",
    ),
    ConnectorToolDef(
        "figma",
        "figma_get_comments",
        "List comments",
        "read",
        "List comments on a file.",
    ),
    ConnectorToolDef(
        "figma",
        "figma_post_comment",
        "Comment",
        "write",
        "Comment on a file.",
        target_arg="file_key",
    ),
    ConnectorToolDef(
        "figma",
        "figma_export_images",
        "Export images",
        "read",
        "Render nodes to image URLs.",
    ),
    ConnectorToolDef(
        "google_drive",
        "drive_search_files",
        "Search files",
        "read",
        "Search Drive files by name or content.",
    ),
    ConnectorToolDef(
        "google_drive",
        "drive_list_folder",
        "List folder",
        "read",
        "List a Drive folder's contents.",
    ),
    ConnectorToolDef(
        "google_drive",
        "drive_read_file",
        "Read file",
        "read",
        "Read a Drive file as text.",
    ),
    ConnectorToolDef(
        "docusign",
        "docusign_list_envelopes",
        "List envelopes",
        "read",
        "List recent envelopes by status.",
    ),
    ConnectorToolDef(
        "docusign",
        "docusign_get_envelope",
        "Read envelope",
        "read",
        "Read an envelope's signer progress.",
    ),
    ConnectorToolDef(
        "docusign",
        "docusign_list_templates",
        "List templates",
        "read",
        "List signature templates.",
    ),
    ConnectorToolDef(
        "docusign",
        "docusign_send_from_template",
        "Send for signature",
        "write",
        "Send a template to a signer.",
        target_arg="recipient_email",
    ),
    ConnectorToolDef(
        "canva",
        "canva_list_designs",
        "List designs",
        "read",
        "List or search designs.",
    ),
    ConnectorToolDef(
        "canva",
        "canva_get_design",
        "Read design",
        "read",
        "Read a design's metadata.",
    ),
    ConnectorToolDef(
        "canva",
        "canva_export_design",
        "Export design",
        "read",
        "Start rendering a design to pdf/png/jpg.",
    ),
    ConnectorToolDef(
        "canva",
        "canva_get_export",
        "Check export",
        "read",
        "Poll an export job for download URLs.",
    ),
)
