"""Security and persistence foundations for the Browser Use runtime."""

from .actions import (
    ActionPolicyDecision,
    ApprovalExpired,
    ApprovalInvalid,
    BrowserActionApproval,
    BrowserActionPolicy,
    BrowserActionPolicyError,
    BrowserActionRequest,
    TargetMetadata,
)
from .destination import (
    CanonicalOrigin,
    DestinationDecision,
    DestinationPolicy,
    DestinationPolicyError,
    canonical_origin,
    canonicalize_url,
    is_explicit_local_origin,
)
from .privacy import (
    BROWSER_INPUT_REDACTED,
    BROWSER_OBSERVATION_OMITTED,
    durable_browser_event,
    is_browser_tool,
    redact_browser_error,
    scrub_browser_audit_event,
    scrub_browser_messages_for_storage,
    scrub_browser_tool_arguments,
)
from .proxy import FailClosedLoopbackProxy, ProxyEndpoint
from .proxy_host import BrowserProxyHost
from .site_permissions import (
    BrowserSiteAccessDecision,
    BrowserSitePermissionStore,
    SiteAccessMode,
    normalize_host,
)
from .vault import (
    BrowserProfileVault,
    BrowserProfileVaultError,
    EncryptedBrowserProfileVault,
    InMemoryKeyProtector,
    InvalidProfileId,
    KeyProtector,
    MacOSKeychainProtector,
    ProfileInUseError,
    ProfileLease,
    VaultCorruptError,
    VaultCryptoUnavailable,
    VaultPermissionError,
    WindowsDPAPIKeyProtector,
    default_key_protector,
)

__all__ = [
    "ActionPolicyDecision",
    "ApprovalExpired",
    "ApprovalInvalid",
    "BROWSER_INPUT_REDACTED",
    "BROWSER_OBSERVATION_OMITTED",
    "BrowserActionApproval",
    "BrowserActionPolicy",
    "BrowserActionPolicyError",
    "BrowserActionRequest",
    "BrowserProfileVault",
    "BrowserProfileVaultError",
    "BrowserProxyHost",
    "BrowserSiteAccessDecision",
    "BrowserSitePermissionStore",
    "CanonicalOrigin",
    "DestinationDecision",
    "DestinationPolicy",
    "DestinationPolicyError",
    "EncryptedBrowserProfileVault",
    "FailClosedLoopbackProxy",
    "InMemoryKeyProtector",
    "InvalidProfileId",
    "KeyProtector",
    "MacOSKeychainProtector",
    "ProfileInUseError",
    "ProfileLease",
    "ProxyEndpoint",
    "SiteAccessMode",
    "TargetMetadata",
    "VaultCorruptError",
    "VaultCryptoUnavailable",
    "VaultPermissionError",
    "WindowsDPAPIKeyProtector",
    "canonical_origin",
    "canonicalize_url",
    "is_explicit_local_origin",
    "normalize_host",
    "default_key_protector",
    "durable_browser_event",
    "is_browser_tool",
    "redact_browser_error",
    "scrub_browser_audit_event",
    "scrub_browser_messages_for_storage",
    "scrub_browser_tool_arguments",
]
